### ISSUE TITLE
Wrong type on json

### ISSUE THREAD

**Issue by Eprince-hub** [ts-safeql/safeql#102]
**Describe the bug**
SafeQL doesn't accept types for json, other than `any`.  Using the `json_agg` aggregate function makes SafeQL think that the returning column must be `any` type and throws an error otherwise.  The query below throws an `incorrect type annotation` if any other type is used for the `returningJson` other than `any`

```ts
type JsonAgg = {
  a: string;
  b: string;
  c: string;
};

type SafeqlRecordWithJson = {
  id: number;
  firstName: string | null;
  lastName: string | null;
  returningJson: JsonAgg;
};

export async function getAllTestSafeqlRecordWithJson() {
  return await sql<SafeqlRecordWithJson[]>`
      SELECT
        *,
      (
        SELECT json_agg(ingredients)::json
        FROM (
        SELECT
          *
        FROM
          try_safe_ql
        )ingredients
      ) AS returning_json
      FROM
        test_safeql;
          `;
}
```

**To Reproduce**

1. Setup SafeQL
2. Use the code above in `.ts` file

**Expected behavior**
I expected that using these kinds of aggregate functions shouldn't cause an error, when i am using the type the query should return or that SafeQL would suggest types other than `any`

**Screenshots**

![Screenshot 2022-11-16 at 08 19 08](https://user-images.githubusercontent.com/74430629/202118207-690beb5c-e0f0-4b9e-8ccd-c298415617ee.png)

![Screenshot 2022-11-16 at 08 18 01](https://user-images.githubusercontent.com/74430629/202118186-51ee7861-78c0-4156-a944-56b42fec4c79.png)

![Screenshot 2022-11-16 at 08 22 16](https://user-images.githubusercontent.com/74430629/202118244-6ad5d4a4-76a8-4d72-a6b2-031870816a0c.png)

**Desktop (please complete the following information):**
- OS: MAC OS
- PostgreSQL version 14

**Additional context**

**Comment by Newbie012** [comment]
Thanks for the feedback! you can change that using [overrides.types](https://safeql.dev/api/index.html#connections-overrides-types-optional):

```json
{
  "connections": {
    // ...
    "overrides": {
      "types": {
        "json": "JsonAgg"
      }
    }
  }
}
```

**Comment by Eprince-hub** [comment]
Hello, @Newbie012. I was exploring the suggestion you made above to solve the issue I am having with `json` type, and I find out that this mapping `"json": "JsonAgg"` doesn't represent the data type that the `json_agg` aggregate function is returning. Please, see the detailed explanation in this PR to confirm if I am correct or if I am missing something
https://github.com/upleveled/eslint-config-upleveled/pull/239

**Comment by Eprince-hub** [comment]
@Newbie012 

Hello, @Newbie012. I was exploring the suggestion you made above to solve the issue I am having with `json` type, and I find out that this mapping `"json": "JsonAgg"` doesn't represent the data type that the `json_agg` aggregate function is returning. Please, see the detailed explanation in this PR. 

Please I want to confirm if I am correct or if I am missing something
https://github.com/upleveled/eslint-config-upleveled/pull/239

**Comment by karlhorky** [comment]
Update from [this comment](https://github.com/ts-safeql/safeql/issues/179#issuecomment-1676060569) by @Newbie012 : in the future, some JSON aggregation options will be supported (maybe also `json_agg`), once SafeQL moves away from `RowDescription`:

> Currently, SafeQL mainly relies on PostgreSQL's [`RowDescription`](https://www.postgresql.org/docs/current/protocol-message-formats.html) which explains the query structure without executing it.
> 
> PostgreSQL idiomatically infers the `post_details` row as `json` (which SafeQL output as `any` [but is configurable](https://safeql.dev/api/#connections-overrides-types-optional)).
> 
> Due to that, SafeQL is unable to infer the exact result of `json_build_object`.
> 
> I'll keep this open since I do plan eventually to support these kinds of limitations by moving away from RowDescription.

**Comment by karlhorky** [comment]
@Newbie012 for the future, one additional idea that I came across while writing [my SQL tooling thread on Twitter/X](https://twitter.com/karlhorky/status/1730113589795549633) was how @kristiandupont handles it in [Kanel](https://github.com/kristiandupont/kanel):

> You can specify the type using a column comment. So if you have a table user with a column address that is JSON(B), you can run
>
> ```sql
> COMMENT ON COLUMN user.address IS '@type:string ..and the rest of your comment, if any';
> ```
>
> and now Kanel should turn it into a string. If you want to specify a type that needs to be imported, you can use `@type(MyType, 'my-library', false, true, false)`

Source: https://github.com/kristiandupont/kanel/issues/429#issuecomment-1636126264

Sounds like it could be nice, to be able to specify the type information in the database 👍

**Comment by Newbie012** [comment]
Hmm.. that's an interesting approach!

Although I feel people won't like commenting code-specific comments in their tables. Maybe I could implement it under a flag.

Another idea, would be to define them in a config. Something like:

```json
{
  "connections": {
    "overrides": {
      "columns": {
        "person.address": "string",
        "person.geolocation": "import('@/types/Geo')"
      }
    }
  }
}
```

Would like to hear your thoughts on this 🙂

**Comment by karlhorky** [comment]
Personally I would lean towards having them in the database:

1. ["Database as the source of truth"](https://github.com/kristiandupont/kanel/issues/429#issuecomment-1636134125) as Kristian mentioned
2. Keeping your types as close as possible to your data is a good thing. We often have multiple different generated JSON fields which should have different types based on what is being returned (sometimes ad-hoc or not a regular representation of a type). Keeping the type next to them would help a lot with creation and also maintenance, as they change over time.
3. It would allow for portability of these types across different projects (to avoid having to configure SafeQL multiple times or share the ESLint config somehow)
4. I think adding this metadata optionally for those who want to add JSON would be an ok thing to ask users to do

But if SafeQL doesn't want this approach and would rather have them defined separately as part of SafeQL config, then we would find a way to live with the feature elsewhere (as long as sufficiently flexible, allowing multiple different possible types returned from JSON fields).

**Comment by Newbie012** [comment]
I understand. My only concern here is that there's no "standard" of defining types in the database comments, which may lead to:

- One tool could use the syntax `... IS '@type:string' while a different tool would use `@type(string)`.
- One database, multiple server packages - each one can define the type differently.

I could allow the option to find the type in the comments by regex while using `@type(...)` as the default.

**Comment by kristiandupont** [comment]
For what it's worth, I am wrote a [parser](https://github.com/kristiandupont/tagged-comment-parser)with Peggy. While it's not a standard, the same syntax is also used by [PostGraphile](https://www.graphile.org/postgraphile/smart-comments/). (Note: that's *tagging* in general, not the `@type` tag specifically).

I think tagging could become a semi-standard if more libraries adopt it so I would be very happy to contribute in that regard. As for types, it's a bit more difficult because even if we agree that this is Postgres-only, other people might want types for other languages where the syntax would inevitably have to be different.

**Comment by Newbie012** [comment]
Thanks for sharing that @kristiandupont.

It seems like the parser is having hard time catching more complex terms:

```ts
import { parse } from "tagged-comment-parser";

const result = parse("@type:number @literal:'a'|'b' @object:{foo:number}");
```

But when I think about it, it doesn't have to. It could return a simple string and then SafeQL could treat it as a "pg" type, which could be transformed to any TypeScript type via [`overrides.types`](https://safeql.dev/api/#connections-overrides-types-optional):

```sql
COMMENT ON COLUMN "user".address IS '@type:geo ...' 
```

```json
{
  "connections": {
    "overrides": {
      "types": {
        "geo": "Geo"
      }
    }
  }
}
```

Since SafeQL should be used only with TypeScript & PostgreSQL, I'm less worried about conflicts with other languages. My issue is there can be potentially too much clutter when multiple clients access a single database.

**Comment by kristiandupont** [comment]
There are some shortcomings for sure, but not necessarily intentional. I am happy to expand on it, I've only been using it for personal stuff so far. The only criterium I have is that tags should be able to live side by side with a "regular" comment.

**Comment by karlhorky** [comment]
@Newbie012 should we rename this issue and reopen to track progress on this?

**Comment by Newbie012** [comment]
It seems more logical to keep this issue closed and open a new one since the original issue doesn't relate to the proposed feature. Using json_agg translates to a json type, which is different from a JSONB column that could correspond to a diverse type.

**Comment by karlhorky** [comment]
Hm, would this `COMMENT` solution not also work for `json_agg` columns?

> It seems more logical to keep this issue closed and open a new one

Can definitely do this, but maybe `json_agg` could be one of the points for investigation + implementation in the new issue?

Proper `json_agg` types continues to be one of the largest challenges of us + students when using SafeQL.

**Comment by Newbie012** [comment]
It won't. `json_agg` is a function, not a type. Meaning, `json_agg` can accept any element. Not just relation).

As previously detailed [here](https://github.com/ts-safeql/safeql/issues/179#issuecomment-1676060569), SafeQL leans on PostgresSQL's RowDescription message for column metadata if available. 

While scanning the query's AST for nullability checks, theoretically, I could simultaneously seek JSON/B expressions and attempt to deduce its type. Simple cases like `json_agg(tbl)` might be inferable, but this is purely speculative. Regardless, an issue reconciling this and https://github.com/ts-safeql/safeql/issues/179 seems necessary, as they both stem from the same issue.

**Comment by karlhorky** [comment]
> While scanning the query's AST for nullability checks, theoretically, I could simultaneously seek JSON/B expressions and attempt to deduce its type. Simple cases like `json_agg(tbl)` might be inferable, but this is purely speculative.

Oh, just thought of something else - not sure if this is the same idea as what you mentioned here:

Running subqueries recursively when they are encountered in the query, to find the type of the data, if the column is type `json`.

**Comment by Newbie012** [comment]
It seems like pg comments aren't parsed [at the moment](https://github.com/pyramation/libpg-query-node/issues/8).

About your suggestion - While I understand how it somewhat solves your issue, It doesn't feel like a future-proof code. Queries are volatile, and comments may get disconnected from the logic. I think gradually adding support for json type inference would be more promising.

**Comment by karlhorky** [comment]
Created a new issue here, feel free to edit as needed:

- https://github.com/ts-safeql/safeql/issues/190

If you don't have objections, I would close #179 with a note that #190 supersedes this.

**Comment by Newbie012** [comment]
Update - https://github.com/ts-safeql/safeql/issues/190#issuecomment-1854912960

**Comment by karlhorky** [comment]
> Thanks for the feedback! you can change that using [overrides.types](https://safeql.dev/api/index.html#connections-overrides-types-optional):
> 
> ```json
> {
>   "connections": {
>     // ...
>     "overrides": {
>       "types": {
>         "json": "JsonAgg"
>       }
>     }
>   }
> }
> ```

If you're using options like `overrides.types.json` or `overrides.types.jsonb` and are having troubles with the `JsonAgg` type only referring to a single TypeScript type, creating multiple files offers a way to work around this:

- https://github.com/ts-safeql/safeql/issues/212#issuecomment-2082628114

**Comment by Newbie012** [comment]
The scanner is a different tool than the parser. While it is more "possible", it will require SafeQL to run both `scan` and `parse` for each query and then try to merge the results, which can be complicated and unreliable. You can play around with the difference between them here - https://pg-query-ast-explorer.vercel.app/
