### ISSUE TITLE
Unexpected type inference on array fields

### ISSUE THREAD

**Issue by Eprince-hub** [ts-safeql/safeql#121]
**Describe the bug**
SafeQL infers `any` type on fields that returns an array, leading to a `Query has incorrect type annotation` error when type `any` is not passed to this field. 
The example below will throw the above error on `FoodNames` because a type other than `any` is being passed
```ts
type AnimalWithFoodName = {
  firstName: string;
  foodNames: string[];
};

export async function queryJsonAgg() {
  return await sql<AnimalWithFoodName[]>`
    SELECT
       first_name,
       (SELECT json_agg(name) FROM foods) AS food_names
    FROM
      animals
  `;
}
```
**To Reproduce**

1. Setup SafeQL
2. Use this code in `.ts` file
```ts
type AnimalWithFoodName = {
  firstName: string;
  foodNames: string[];
};

export async function queryJsonAgg() {
  return await sql<AnimalWithFoodName[]>`
    SELECT
       first_name,
       (SELECT json_agg(name) FROM foods) AS food_names
    FROM
      animals
  `;
}
```
**Expected behavior**
I expect that SafeQL doesn't throw an error when the correct type is being passed and should infer the correct type
Using type `any` is not encouraged in TypeScript and should also be discouraged in SafeQL

**Screenshots**
Incorrect type annotation error when the correct type is passed
![Screenshot 2023-04-11 at 10 08 05](https://user-images.githubusercontent.com/74430629/231097253-445ee8a7-c57f-436e-9452-7efc63888792.png)

No error when `any` type is passed
![Screenshot 2023-04-11 at 10 09 20](https://user-images.githubusercontent.com/74430629/231097467-6c5db52e-46ff-4dfd-8124-b0b596ebeeed.png)

**Desktop (please complete the following information):**
 - OS: MAC OS
 - PostgreSQL version 15

**Additional context**

**Comment by Newbie012** [comment]
`json_agg` method returns a json, which by default I map to `any` since the majority of the Typescript community prefer `any` over `unknown`. But you could change that behavior in the [overrides.types](https://safeql.dev/api/index.html#connections-overrides-types-optional).

What you want is `array_agg` instead:

```ts
type AnimalWithFoodName = {
  firstName: string;
  foodNames: string[];
};

export async function queryJsonAgg() {
  return await sql<AnimalWithFoodName[]>`
    SELECT
       first_name,
       (SELECT array_agg(name) FROM foods) AS food_names
    FROM
      animals
  `;
}
```

**Comment by Eprince-hub** [comment]
Thank you, @Newbie012, I will give this a try
