### ISSUE TITLE
Unexpected error on field with type Date

### ISSUE THREAD

**Issue by Eprince-hub** [ts-safeql/safeql#123]
**Describe the bug**
SafeQL throws an `Invalid Query: the type "Date" is not supported` when inserting a record that has a type `Date` resulting to the code below throwing the above error on the `foodToInsert.createdTimeStamp`

```ts
type FoodInsertInput = {
  name: string;
  cuisine: string;
  createdTimeStamp: Date;
};

export async function createFood(foodToInsert: FoodInsertInput) {
  return await sql`
    INSERT INTO foods
      (name, cuisine, created_timestamp)
    VALUES
      (${foodToInsert.name}, ${foodToInsert.cuisine}, ${foodToInsert.createdTimeStamp})
    RETURNING *
  `;
}
```

**To Reproduce**

1. Setup SafeQL
2. Use this code in `.ts` file
3. Insert a record with type `Date` 

```ts
type FoodInsertInput = {
  name: string;
  cuisine: string;
  createdTimeStamp: Date;
};

export async function createFood(foodToInsert: FoodInsertInput) {
  return await sql`
    INSERT INTO foods
      (name, cuisine, created_timestamp)
    VALUES
      (${foodToInsert.name}, ${foodToInsert.cuisine}, ${foodToInsert.createdTimeStamp})
    RETURNING *
  `;
}
```

**Expected behavior**
I expect that inserting a record with the type `Date` should not produce the `Invalid Query` error

**Screenshots**
![Screenshot 2023-04-11 at 11 32 40](https://user-images.githubusercontent.com/74430629/231118352-b05a8e08-ff22-4621-af37-7a865f4c4126.png)

Some workaround considered
1. Making the `createdTimeStamp` property a type `string` but got `Invalid Query: column "created_timestamp" is of type timestamp without time zone but expression is of type text` error
![Screenshot 2023-04-11 at 12 09 37](https://user-images.githubusercontent.com/74430629/231129236-405a6eff-937c-4379-b0e2-fab9c9e72411.png)

2. type casting the `createdTimeStamp` , all the same error like the one above
![Screenshot 2023-04-11 at 12 11 15](https://user-images.githubusercontent.com/74430629/231129653-9047ba45-ba2c-4684-bb87-9697ec8c7b0f.png)

   ![Screenshot 2023-04-11 at 12 12 53](https://user-images.githubusercontent.com/74430629/231130074-6fdd3b44-34ed-4027-9176-713fe5d910a0.png)

**Desktop (please complete the following information):**
 - OS: MAC OS
 - PostgreSQL version 15

**Additional context**

**Comment by Newbie012** [comment]
Another workaround would be to add it to [overrides.types](https://safeql.dev/api/#connections-overrides-types-optional) as introduced in [0.0.23](https://github.com/ts-safeql/safeql/releases/tag/%40ts-safeql%2Feslint-plugin%400.0.23)

The original issue was that when I get a type date, what do I cast it to? `timestamp`? `timestamptz`? `date`?
In any case, I created a [PR](https://github.com/ts-safeql/safeql/pull/124) that should address this as follows:

1. Make the error more descriptive to point to `overrides.types`.
2. Attach the default mapping so `Date` would be mapped appropriately (and could be overridden by settings).
3. Add an example.

**Comment by Eprince-hub** [comment]
Thank you for the quick response
