### ISSUE TITLE
`name` should support nested objects

### ISSUE THREAD

**Issue by fingeromer** [ts-safeql/safeql#131]
`@ts-safeql/check-sql` rule supports only first-level objects as db connection handler object. 
For example, 
```
connections: [
          { ..., name: 'entityManager' }
]
```
`entityManager.query('SELECT * FROM a')`

Ir doesn't support nested objects: 
```
connections: [
          { ..., name: 'this.a.entityManager' }
]
```
`this.a.entityManager('SELECT * FROM a')`

A possible solution is to support only the last object, that calls the `query` method: 
```
connections: [
          { ..., name: 'entityManager' }
]
```

Will match `this.a.entityManager.query()`, `a.entityManager.query()`, `entityManager.query()`

**Comment by Newbie012** [comment]
resolved in 1.0.0
