### ISSUE TITLE
Allow disabling type annotation fix

### ISSUE THREAD

**Issue by rhenriquez28** [ts-safeql/safeql#144]
**Is your feature request related to a problem? Please describe.**
Slonik provides various tagged template literal primitives that allow us to write SQL. In particular, it has a `sql.type` to pass Zod schemas to define the shape of the query return value and `sql.typeAlias` to have a predefined set of Zod schemas to use with our queries. `sql.type` and `sql.typeAlias` are not normal generics because they aren't supposed to accept generic arguments, rather that they infer what it's passed to them via their arguments. When I use SafeQL with Slonik, the type annotation fix keeps appearing even though I have no need to add the annotation since I'm already using my Zod schemas:

<img width="940" alt="Screenshot 2023-05-07 at 10 39 58 AM" src="https://user-images.githubusercontent.com/22778956/236687658-882466e8-23a9-4707-8ac0-a9b4a4c949b7.png">

**Describe the solution you'd like**
A potential solution for this would be to have an `overrides.skipTypeAnnotation` option in the SafeQL config that would allow us to skip this suggestion in case a person is using Slonik or another library where they don't need it. API could be something like:

```ts
{
  "connections": {
    "overrides": {
      "skipTypeAnnotation": true, // if you want to skip type annotation for every tag or wrapper you have
      //or
      "skipTypeAnnotaion": [{ "tag": "sql.type\\(*\\)" }] // if you want to skip type annotation for specific tag or wrapper
    }
  }
}
```

**Describe alternatives you've considered**
Another way would be to add the "skipTypeAnnotation" option when we are specifying the tag or wrapper in the targets array:
```ts
{
  "connections": {
    "targets": [
      {
        "tag": "sql.+(type\\(*\\)|typeAlias\\(*\\)|unsafe)",
        "skipTypeAnnotation": true
      }
    ]
  }
}
```

**Comment by Newbie012** [comment]
Sounds like a nice way of integrating SafeQL with Slonik 🙂
Should be `skipTypeAnnotations` will be released in the next version.
