### ISSUE TITLE
Can't insert value with `type | null` typing

### ISSUE THREAD

**Issue by rhenriquez28** [ts-safeql/safeql#145]
**Describe the bug**
SafeQL does infer correctly the return type of my query here, especially with the `document_storage_id` column, which has a definition of 
```sql
document_storage_id INTEGER REFERENCES Public.Document_Storage(storage_id)
```
and SafeQL infers it correctly as `number | null`
<img width="934" alt="Screenshot 2023-05-07 at 11 18 27 AM" src="https://user-images.githubusercontent.com/22778956/236689595-ff1236c5-970f-43a2-abaf-6fe13403030a.png">

However, when I try to insert or update the value, I get the following error:
<img width="840" alt="Screenshot 2023-05-07 at 11 18 54 AM" src="https://user-images.githubusercontent.com/22778956/236689611-b959b1f0-4fd7-4d1e-93f6-875bdb48ec75.png">

SafeQL doesn't even allow to pass a straight-up `null`:
<img width="705" alt="Screenshot 2023-05-07 at 11 27 16 AM" src="https://user-images.githubusercontent.com/22778956/236690038-5662b80e-4128-4466-87db-e992d0e0565f.png">

I don't know a lot about PostgreSQL and this most likely is a side effect of the fact that I think NULL isn't actually a PostgreSQL type. But there's gotta be a way around this, since this is a very common thing. I tried doing what the error recommended like:
```ts
{
  "connections": {
    ...,
    "overrides": {
      "types": {
        NULL: "null"
      }
    }
  }
}
```

But eslint crashes and I think due to my understanding that NULL isn't actually a PostgreSQL type

**To Reproduce**
1. Create a table that has a nullable column
2. Write an INSERT or UPDATE statement with the column and the type of the value you want to insert being `<type> | null`
3. See the error

**Expected behavior**
I should be able to insert or update with values that have a `null` or `type | null` typing if the column doesn't have a `NOT NULL` in its definition

**Desktop (please complete the following information):**
 - OS: macOS 13.3.1
 - PostgreSQL version 14.2
 - Version ^1.0.2

**Comment by rhenriquez28** [comment]
Hey @Newbie012, thank you very very much for your quick fixes to the issues I raised. I'm very excited to integrate this at my job. It will help us a ton.

Just wanted to say that although you did fix the `number | null` issue, I still can't pass just a `null` to SQL since we arrive at the same `Invalid Query: The type "null" has no corresponding PostgreSQL type` error. Would still need to check how to fix that

**Comment by Newbie012** [comment]
Oh, open a new issue and I'll raise a PR tomorrow 👍
