### ISSUE TITLE
Support INTERVAL type

### ISSUE THREAD

**Issue by fingeromer** [ts-safeql/safeql#162]
**Is your feature request related to a problem? Please describe.**
![image](https://github.com/ts-safeql/safeql/assets/112797342/de7704ff-25ab-4e6b-b06c-3df7b8da656b)

**Describe the solution you'd like**
I would like `interval '${number} minutes/hours/etc..'` to act like a valid interval type.

**Comment by Newbie012** [comment]
It's a bit tricky since each library behaves somewhat differently. The easiest solution is to cast to interval instead of using a prefix:

```ts
const interval = "1 day 2 hours 3 minutes 4 seconds";
await sql`SELECT now() - ${interval}::interval as my_interval`;
```

This approach appears to work as expected with both SafeQL and runtime.
