### ISSUE TITLE
Incorrect Type Inference for JOIN Query

### ISSUE THREAD

**Issue by Eprince-hub** [ts-safeql/safeql#171]
**Describe the bug**
SafeQL is inferring an incorrect type annotation for a query involving LEFT/FULL JOIN. Specifically, it incorrectly implies that the `foodAnimalId` field should be of type `number | null`,  and throws an `Query has incorrect type annotation.` error otherwise. It also throws the same error when any of the JOIN are used together like in the last code below

**To Reproduce**

1. Setup SafeQL
2. Use any of the code below in `.ts` file

```ts
export async function leftJoin() {
  return await sql<AnimalWithFood[]>`
    SELECT
      animals.id AS food_animal_id
    FROM
      foods
    LEFT JOIN
      animal_foods ON animal_foods.food_id = foods.id
    LEFT JOIN
      animals ON animals.id = animal_foods.animal_id
  `;
}
// OR

export async function fullJoin() {
  return await sql<AnimalWithFood[]>`
    SELECT
      animals.id AS food_animal_id
    FROM
      foods
    FULL JOIN
      animal_foods ON animal_foods.food_id = foods.id
    FULL JOIN
      animals ON animals.id = animal_foods.animal_id
  `;
}
// OR
export async function innerJoinAndLeftJoin() {
  return await sql<AnimalWithFood[]>`
    SELECT
      animals.id AS food_animal_id
    FROM
      foods
    INNER JOIN
      animal_foods ON animal_foods.food_id = foods.id
    LEFT JOIN
      animals ON animals.id = animal_foods.animal_id
  `;
}
```
The same query written with `no join`, or `RIGHTJOIN` or `INNER JOIN` did not have the issue
```ts
export async function innerJoin() {
  return await sql<AnimalWithFood[]>`
    SELECT
      animals.id AS food_animal_id
    FROM
      foods
    INNER JOIN
      animal_foods ON animal_foods.food_id = foods.id
    INNER JOIN
      animals ON animals.id = animal_foods.animal_id
  `;
}
// OR
export async function rightJoin() {
  return await sql<AnimalWithFood[]>`
    SELECT
      animals.id AS food_animal_id
    FROM
      foods
    RIGHT JOIN
      animal_foods ON animal_foods.food_id = foods.id
    RIGHT JOIN
      animals ON animals.id = animal_foods.animal_id
  `;
}
// OR
export async function noJoin() {
  return await sql<AnimalWithFood[]>`
    SELECT
      animals.id AS food_animal_id
    FROM
      foods,
      animal_foods,
      animals
    WHERE
      foods.id = animal_foods.food_id
    AND
      animals.id = animal_foods.animal_id
  `;
}
```

**Expected behavior**

**Screenshots**
![Screenshot 2023-07-27 at 15 00 04](https://github.com/ts-safeql/safeql/assets/74430629/d423e74e-639d-4b8d-89df-e46a2bc0598d)

![Screenshot 2023-07-27 at 15 06 39](https://github.com/ts-safeql/safeql/assets/74430629/84668323-1a22-465c-9c8c-3319eb5e9803)

![Screenshot 2023-07-27 at 15 01 04](https://github.com/ts-safeql/safeql/assets/74430629/53256c94-6cde-48a7-b4a7-3ba93e11434d)

The same query with
![Screenshot 2023-07-27 at 15 01 38](https://github.com/ts-safeql/safeql/assets/74430629/4efcf8d8-32fc-4712-b8b3-181bd413f825)

**Desktop (please complete the following information):**
 - OS: [MacOS]
 - PostgreSQL version [15.3]
 - SafeQL Version [2.0.0]

**Additional context**

**Comment by Newbie012** [comment]
In a `LEFT JOIN` operation, if a record in the left table (`foods` in this case) does not have a corresponding record in the right table (`animal_foods` and `animals` in this case), the query will return null for all columns of the right table.

So, even though `animals.id` is non-nullable, the LEFT JOIN can introduce nulls in the result set for `animals.id` if there's no corresponding record in `animal_foods` table.

Why not use INNER JOIN in your first case? I'm probably missing something.

**Comment by Eprince-hub** [comment]
Thank you for your response and explanation. You are correct, and I understand your points above. 

Using INNER JOIN would exclude food items with no associated animals in the animal_foods and animals tables. In some cases, we may want to see all food items, even if they are not associated with any specific animal, and that's why I thought using the LEFT JOIN would be the way to achieve that, or is my approach with LEFT JOIN wrong in this case? I guess in that case, we would have to define our type in a way that would make SafeQL happy🤔

**Comment by Newbie012** [comment]
It really depends on what you want to fetch. There's no need to "make SafeQL happy", it annotates the correct type.

If you want to select all of the food records and pair animals when possible, `animals` records will be potentially nullable since they may not exist. Your assumption about `LEFT JOIN` is correct.

If you want to add a fallback to a nullable value, you could use a `COALESCE` expression

**Comment by Eprince-hub** [comment]
Thanks a lot for the insight. I will think more about what this data means to me business-wise, and if I expect it to be null sometimes,  I will redefine my type. If not, I will change my approach.
