### ISSUE TITLE
Incremental adoption TypeORM with Nest.js

### ISSUE THREAD

**Issue by simplenotezy** [ts-safeql/safeql#185]
We are using TypeORM for our project in a Nest.js application and are missing some instructions for setting up incremental adption (https://safeql.dev/advanced/incremental-adoption.html) with TypeORM

**Comment by simplenotezy** [comment]
I've tried something like this, inside a service:

```ts
  $typedQueryRaw(query: string, parameters?: any[], queryRunner?: QueryRunner) {
    return this.dataSource.query(query, parameters, queryRunner);
  }
  
  someMethod() {
  const query = await this.$typedQueryRaw`SELECT * FROM "user"`
  }
```
  
With the following setup:
  
```
  targets: [{ tag: '$typedQueryRaw', transform: '{type}[]' }],
```
  
However, I am getting this error:

```
Argument of type 'TemplateStringsArray' is not assignable to parameter of type 'string'.ts(2345)
```

**Comment by Newbie012** [comment]
This is somewhat related to https://github.com/ts-safeql/safeql/discussions/108

TypeORM currently doesn't support [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals). I opened a [PR](https://github.com/typeorm/typeorm/pull/10108) on TypeORM, but I haven't received any official reply from them.

In any case, I added a [TypeORM demo](https://github.com/ts-safeql/safeql/tree/main/demos/typeorm) with a workaround until the mentioned-above PR will be merged.

```ts
import { sql as SafeQLTag } from "@ts-safeql/sql-tag";
import { DataSource } from "typeorm";
import { AppDataSource } from "./data-source";

function createDataSourceSqlTag(dataSource: DataSource) {
  return <TValue>(template: TemplateStringsArray, ...values: unknown[]): Promise<TValue> => {
    const tag = SafeQLTag(template, ...values);
    return dataSource.query<TValue>(tag.query, tag.values);
  };
}

const sql = createDataSourceSqlTag(AppDataSource);
```
view [source](https://github.com/ts-safeql/safeql/blob/main/demos/typeorm/src/index.ts).
