### ISSUE TITLE
Wrong type predictions

### ISSUE THREAD

**Issue by MatanOligo** [ts-safeql/safeql#194]
**Describe the bug**
When using aggregators the type prediction is not correct.

**To Reproduce**
Just write a query with an aggregator.

**Expected behavior**
The value returned is an array of rows, with only one index containing the aggregated result.
So the result type should be array. Not a primitive value.

**Screenshots**
![image (6)](https://github.com/ts-safeql/safeql/assets/132813026/c196b0b5-5642-4d6a-94e2-4c7b7a368a46)
![image (7)](https://github.com/ts-safeql/safeql/assets/132813026/bf508458-b146-4ce5-b55f-80f7f9e648fa)

**Desktop (please complete the following information):**
 - OS: OS
 - PostgreSQL version: 14
 - Version: 2.0.3

**Comment by karlhorky** [comment]
1. maybe you should remove the `[]` in your type
2. for the `null` mismatch, you may want to check out this detail about SafeQL "everything is nullable until proven otherwise" behavior https://github.com/ts-safeql/safeql/issues/192#issuecomment-1842667108

**Comment by Newbie012** [comment]
1. `count` can never be `null` (unlike other aggregation functions such as `sum`).
2. Just like @karlhorky mentioned, it seems like you have a `transform: "{type}[]"` in your configuration. If your generic does not require an array, (which seems like your case), you can remove it from the configuration.
