### ISSUE TITLE
Wrong type generation / inference when joining a table with itself

### ISSUE THREAD

**Issue by lunedis** [ts-safeql/safeql#204]
Awesome library, been using it quite extensively for the rewrite of some of my projects!

**Describe the bug**
`ts-safeql` generates wrong types when **LEFT** joining a table with itself.

**To Reproduce**

example db:
```sql
CREATE TABLE employees (
  id INT NOT NULL,
  name VARCHAR NOT NULL,
  boss_id INT
);

INSERT INTO 
  employees (id, name, boss_id) 
VALUES 
  (1, 'Big Boss', NULL),
  (2, 'Employee 1', 1),
  (3, 'Independent Guy', NULL);
  ```

example code:
```typescript

// ts-safeql generated wrong type assertions
sql<{ id: number | null; name: string | null; bossName: string | null; }[]>`
    SELECT 
      employees.id,
      employees.name,
      bosses.name AS boss_name
    FROM employees
    LEFT OUTER JOIN employees AS bosses ON (employees.boss_id = bosses.id);`;
```

reproduction repo: https://github.com/lunedis/safeql-recursive-bug

**Expected behavior**
I expected the resulting type to be
```typescript
{ id: number; name: string; bossName: string | null; }[]
```

This is also the type that gets returned if I do not join the table with itself, or if I use a `LEFT JOIN` with a table that is not the same table.

This happens in both version `2.0.3` and `3.0.0-next.4`.

Using postgres 16.2 (see reproduction repo).

**Comment by Newbie012** [comment]
Thanks for the detailed reproduction. I'll raise a fix.

**Comment by lunedis** [comment]
Thank you for the quick response, but I don't believe the issue is actually fixed.

Weirdly enough in my main (internal) project, it still generates the "main table" fields with `| null` (which I think is wrong).

I updated my reproduction repository (https://github.com/lunedis/safeql-recursive-bug) and now it thinks `bossName` is not nullable (https://github.com/lunedis/safeql-recursive-bug/blob/main/src/main.ts#L10), which I think is also wrong.

Sadly I haven't gotten around to digging into your codebase, else I'd try to fix it myself.

**Comment by Newbie012** [comment]
Hey @lunedis, I cloned and followed your instructions in the README.md and this is what I get when running eslint:

![image](https://github.com/ts-safeql/safeql/assets/10504365/f003a715-c9db-47df-9813-2e80ca592b17)

After fixing the types, eslint doesn't report any other errors:

![image](https://github.com/ts-safeql/safeql/assets/10504365/8d84c6a9-f7f7-4095-b58e-9a59b616132f)

I already have a test that covers this case:

https://github.com/ts-safeql/safeql/blob/2f8b8163d54e7fd2bb0df4e1deb7fe8f57092716/packages/generate/src/generate.test.ts#L1155-L1176

Can you share with me a failing CI execution so I could better reproduce the error?

**Comment by lunedis** [comment]
You are correct, everything seems to work now. Sorry for the confusion, was most likely an old version or database problem on my part. My bad.

The issues in both my reproduction repository and my main project are fixed. Thanks a lot again for the quick response and for developing this awesome tool!
