### ISSUE TITLE
wrapper configuration is being ignored

### ISSUE THREAD

**Issue by satanshiro** [ts-safeql/safeql#226]
**Describe the bug**
in eslint flat config when i configure a wrapper it does not work, the type enforcement is applied only on the sql tag and not the wrapper function

**To Reproduce**
use the following configuration 
![image](https://github.com/ts-safeql/safeql/assets/38865738/8867417c-e2ec-4336-84ce-f81ab5150045)
then notice that the fix is applied only to the sql tag and not the wrapper 
![image](https://github.com/ts-safeql/safeql/assets/38865738/cb2d1afa-d807-4244-b2a4-33ccbcf931e6)
![image](https://github.com/ts-safeql/safeql/assets/38865738/71edb7ac-c29d-41b3-99f0-6723c9c2a333)

**Expected behavior**
the typings check to be applied on the wrapper

**Comment by Newbie012** [comment]
It's unrelated to the flat config. It seems like you've specified 2 targets.

1. for a wrapper
2. for an sql tag

According to your issue description, I'm not sure why you've specified the second target. Try removing the tag target from your config.

**Comment by satanshiro** [comment]
@Newbie012 it is resulting in the same problem
 basically I am exporting a tag named SQL to work with typeorm 
<img width="500" alt="image" src="https://github.com/ts-safeql/safeql/assets/38865738/9dea9a9d-418c-40c1-9b43-86a2e8ed1e30">

reverting back to using safeql tag also doesn't work

**Comment by Newbie012** [comment]
can you share a minimal reproduction?
