### ISSUE TITLE
Invalid Query: Parser services are not available

### ISSUE THREAD

**Issue by ecosse3** [ts-safeql/safeql#229]
**Describe the bug**
On each query I get error:
```
Invalid Query: Parser services are not available [@ts-safeql/check-sql]
```

**To Reproduce**
Just connect to `postgres.js` database via databaseUrl

**Expected behavior**
Should work.

**Desktop (please complete the following information):**
 - OS: macOS
 - PostgreSQL version 14
 
**Additional context**
Connecting to external URL postgres database URL string

**Comment by Newbie012** [comment]
Can you share your eslint config? it seems like you haven't enabled [`parserServices`](https://typescript-eslint.io/getting-started/typed-linting/)

**Comment by ecosse3** [comment]
I was missing `parserServices`, fixed it. Thank you!
