### ISSUE TITLE
Unexpected SafeQL crash when Database Server is not started

### ISSUE THREAD

**Issue by Eprince-hub** [ts-safeql/safeql#230]
**Describe the bug**
SafeQL crashes with an `internal error:` when the Postgres database server is not started/running.

**To Reproduce**

- Clone Project:
```bash
git clone https://github.com/Eprince-hub/safeql-simple-repro
```
- Install dependencies
- Check the `database.ts` file for the reported error

**Expected behavior**
SafeQL shouldn't crash but rather provide a useful error message. Right now, it only says `Internal error:`

**Screenshots**

<img width="1920" alt="Screenshot 2024-06-10 at 10 55 24" src="https://github.com/ts-safeql/safeql/assets/74430629/9e265cfb-f1cd-49b1-bee0-00b19793ccd4">

<img width="1118" alt="Screenshot 2024-06-07 at 16 58 01" src="https://github.com/ts-safeql/safeql/assets/74430629/df9d6f95-c2fb-48a4-83e7-39591e9d2084">

Video

https://github.com/ts-safeql/safeql/assets/74430629/a68abc5b-1156-4bc8-a13b-db8100d3c10c

**Desktop (please complete the following information):**
 - OS: macOS
 - PostgreSQL version 15.7

**Additional context**

**Comment by Newbie012** [comment]
Getting different results:

```
/.../safeql/demos/basic-migrations-raw/src/index.ts
  13:6  error  createdb: error: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
        Is the server running on that host and accepting TCP/IP connections?
  @ts-safeql/check-sql
  23:6  error  Internal error: connect ECONNREFUSED 127.0.0.1:5432                                                                                                                            @ts-safeql/check-sql
  32:6  error  Internal error: connect ECONNREFUSED 127.0.0.1:5432                                                                                                                            @ts-safeql/check-sql
  ```
    
![image](https://github.com/ts-safeql/safeql/assets/10504365/365b3120-8469-414f-9fb3-f22b0be7e708)

can you share a reproduction link?

**Comment by Eprince-hub** [comment]
@Newbie012
Thanks for the quick response, I created a repro for this issue, Issue updated accordingly

https://github.com/Eprince-hub/safeql-simple-repro
