### ISSUE TITLE
Selecting arrays yields nullable type

### ISSUE THREAD

**Issue by timvandam** [ts-safeql/safeql#235]
**Describe the bug**

When selecting an array column (eg VARCHAR(255)[]) the inferred type is nullable, even when the column is non nullable.

**To Reproduce**

```ts
await sql`
    CREATE TABLE users
    (
        id         SERIAL PRIMARY KEY,
        public_id  VARCHAR(255) UNIQUE NOT NULL,
        username   VARCHAR(255) UNIQUE NOT NULL,
        roles      VARCHAR(255)[]      NOT NULL,
        created_at TIMESTAMPTZ         NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ         NOT NULL DEFAULT NOW()
    );`;
```

```ts
// this is the inferred type, but it should be string[]
const [user] = await sql<{ public_id: string; username: string; roles: string[] | null }>`
    SELECT public_id, username, roles
    FROM users
    WHERE public_id = ${publicId}
    LIMIT 1;`;
```

**Expected behavior**

It should yield `roles: string[]`

**Screenshots**

**Desktop (please complete the following information):**
 - PostgreSQL version [e.g. 13, 14]

**Additional context**

I've checked whether postgres can somehow return NULL here, but it seems not.
Inserting NULL is also not possible, i.e.
```sql
insert into users (public_id, username, roles)
VALUES ('test', 'test', NULL);
```
fails

**Comment by timvandam** [comment]
Closing for now since this seems to have fixed itself

**Comment by Newbie012** [comment]
Technically, it is possible that an array would contain null values:

```
CREATE TEMP TABLE example_table (
    id SERIAL PRIMARY KEY,
    array_column TEXT[]
);

INSERT INTO example_table (array_column) VALUES
('{"element1", NULL, "element3"}'),
('{"element4", "element5", NULL}'),
(NULL);

select * from example_table;
```

maybe I should add a `strict.*` options

**Comment by timvandam** [comment]
In your table you do not have a NOT NULL on array_column. If I add that the insert fails

**Comment by Newbie012** [comment]
Oh you're right... my bad

**Comment by Newbie012** [comment]
Oh wait, I wasn't wrong:

```
DROP TABLE IF EXISTS example_table;

CREATE TEMP TABLE example_table (
    id SERIAL PRIMARY KEY,
    array_column TEXT[] NOT NULL
);

INSERT INTO example_table (array_column) VALUES
('{"element1", NULL, "element3"}'),
('{"element4", "element5", NULL}');

select * from example_table;
```

**Comment by timvandam** [comment]
A I see what you mean now, but then the type would is still wrong. I got `roles: string[] | null` instead of `roles: (string | null)[]`. However I'm getting `string[]` now

**Comment by Newbie012** [comment]
Yeah, the original issue was probably due to a caching issue, restarting ESLint would fix that.

In any case, As I wrote previously, I might consider adding strict flags, or change the behavior with a major version
