### ISSUE TITLE
SafeQL Reports Error for Nullable Fields on  boolean

### ISSUE THREAD

**Issue by Eprince-hub** [ts-safeql/safeql#242]
**Describe the bug**
SafeQL throws an `Incorrect type annotation` error when a boolean field is also allowed to be null. Querying the `is_admin` field of the database table below with the type `isAdmin: boolean | null`  will throw the error

```sql
CREATE TABLE animals (
  is_admin boolean
)
```

```ts

export type Animal = {
  isAdmin: boolean | null;
};

// showing incorrect type annotation error
export async function getAnimal() {
  return await sql<Animal[]>`
    SELECT
      animals.is_admin
    FROM
      animals
  `;
}
```

**To Reproduce**

1. Clone https://github.com/Eprince-hub/safeql-simple-repro
2. Replace the `public` env variables with your database credentials
3. Check the code in the `database.ts` file

**Expected behavior**
There may be some cases where the union type of `boolean | null` is needed, and SafeQL should support that. So there shouldn't be an error when I have a field like this `is_admin boolean` and a type like this `isAdmin: boolean | null`

**Screenshots**
<img width="1346" alt="Screenshot 2024-07-05 at 14 23 08" src="https://github.com/ts-safeql/safeql/assets/74430629/59b0ac16-88b3-4966-9ed4-b5caa686f2cd">

**Desktop (please complete the following information):**
 - OS: macOS
 - PostgreSQL version 15.7

**Additional context**

**Comment by karlhorky** [comment]
@Newbie012 what do you think about this one?

I can confirm that this can be reproduced with a nullable `boolean` field (without `NOT NULL`).

It appears that SafeQL is reading the TS type `boolean | null` to be `null | false | true`, which fails equality test with `null | boolean` from PostgreSQL inference.

Is it a small change in SafeQL to infer `null | false | true` instead of `boolean | null` from the TS type?

**Comment by karlhorky** [comment]
## Workaround

Use `Omit<>` and a TypeScript intersection:

```diff
 export type Animal = {
   isAdmin: boolean | null;
 };

 export async function getAnimal() {
-  return await sql<Animal[]>`
+  return await sql<(Omit<Animal, 'isAdmin'> & { isAdmin: boolean | null })[]>`
     SELECT
       animals.is_admin
     FROM
       animals
   `;
 }
```

**Comment by karlhorky** [comment]
@Newbie012 thanks for the PR #264 and the release!

I can confirm that [`@ts-safeql/eslint-plugin@3.4.3`](https://github.com/ts-safeql/safeql/releases/tag/%40ts-safeql%2Feslint-plugin%403.4.3) is working with nullable `boolean` fields 🎉
