### ISSUE TITLE
Unable to install using npm

### ISSUE THREAD

**Issue by Vishal-beep136** [ts-safeql/safeql#255]
**Describe the bug**
I can't install using npm by this script

```
npm install --save-dev @ts-safeql/eslint-plugin libpg-query
```

does this library require Python to be installed on the machine??

because I got this error -> 

```
npm warn deprecated npmlog@5.0.1: This package is no longer supported.
npm warn deprecated are-we-there-yet@2.0.0: This package is no longer supported.
npm warn deprecated gauge@3.0.2: This package is no longer supported.

npm error code 1
npm error path D:\app\backend-nestjs\node_modules\libpg-query
npm error command failed
npm error command C:\WINDOWS\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build        
npm error Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\USER NAME\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=D:\app\backend-nestjs\node_modules\libpg-query\build\Release\queryparser.node --module_name=queryparser --module_path=D:\app\backend-nestjs\node_modules\libpg-query\build\Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v115' (1)
npm error node-pre-gyp info it worked if it ends with ok
npm error node-pre-gyp info using node-pre-gyp@1.0.11
npm error node-pre-gyp info using node@20.16.0 | win32 | x64
npm error node-pre-gyp info check checked for "D:\app\backend-nestjs\node_modules\libpg-query\build\Release\queryparser.node" (not found)
npm error node-pre-gyp http GET https://supabase-public-artifacts-bucket.s3.amazonaws.com/libpg-query-node/queryparser-v16.2.0-node-v115-win32-x64.tar.gz
npm error node-pre-gyp ERR! install response status 404 Not Found on https://supabase-public-artifacts-bucket.s3.amazonaws.com/libpg-query-node/queryparser-v16.2.0-node-v115-win32-x64.tar.gz
npm error node-pre-gyp WARN Pre-built binaries not installable for libpg-query@16.2.0 and node@20.16.0 (node-v115 ABI, unknown) (falling back to source compile with node-gyp)
npm error node-pre-gyp WARN Hit error response status 404 Not Found on https://supabase-public-artifacts-bucket.s3.amazonaws.com/libpg-query-node/queryparser-v16.2.0-node-v115-win32-x64.tar.gz
npm error gyp info it worked if it ends with ok
npm error gyp info using node-gyp@10.1.0
npm error gyp info using node@20.16.0 | win32 | x64
npm error gyp info ok
npm error gyp info it worked if it ends with ok
npm error gyp info using node-gyp@10.1.0
npm error gyp info using node@20.16.0 | win32 | x64
npm error gyp ERR! find Python
npm error gyp ERR! find Python Python is not set from command line or npm configuration
npm error gyp ERR! find Python Python is not set from environment variable PYTHON
npm error gyp ERR! find Python checking if the py launcher can be used to find Python 3
npm error gyp ERR! find Python - executable path is ""
npm error gyp ERR! find Python - "" could not be run
npm error gyp ERR! find Python checking if "python3" can be used
npm error gyp ERR! find Python - executable path is ""
npm error gyp ERR! find Python - "" could not be run
npm error gyp ERR! find Python checking if "python" can be used
npm error gyp ERR! find Python - executable path is ""
npm error gyp ERR! find Python - "" could not be run
npm error gyp ERR! find Python checking if Python is C:\Users\USER NAME\AppData\Local\Programs\Python\Python311\python.exe
npm error gyp ERR! find Python - version is ""
npm error gyp ERR! find Python - version is  - should be >=3.6.0
npm error gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
npm error gyp ERR! find Python - "C:\Users\USER NAME\AppData\Local\Programs\Python\Python311\python.exe" could not be run
npm error gyp ERR! find Python checking if Python is C:\Program Files\Python311\python.exe
npm error gyp ERR! find Python - version is ""
npm error gyp ERR! find Python - version is  - should be >=3.6.0
npm error gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
npm error gyp ERR! find Python - "C:\Program Files\Python311\python.exe" could not be run
npm error gyp ERR! find Python checking if Python is C:\Users\USER NAME\AppData\Local\Programs\Python\Python311-32\python.exe
```

**Desktop (please complete the following information):**
 - OS: Windows 11
 - PostgreSQL version [e.g. 13, 14]

**Comment by Newbie012** [comment]
since there's no pre-compiled libpg-query build for your OS (Windows 11), it tries to compile it on your end using Python. Although, it appears like you don't have Python installed on your machine

**Comment by karlhorky** [comment]
To get Python and other build tools installed on Windows, you may want to consider [installing Chocolatey](https://docs.chocolatey.org/en-us/choco/setup/)

If you did this, you could use the following command to install [`python`](https://community.chocolatey.org/packages/python) and [`visualstudio2022-workload-vctools`](https://community.chocolatey.org/packages/visualstudio2022-workload-vctools):

```bash
choco install python visualstudio2022-workload-vctools -y
```

**Comment by karlhorky** [comment]
@Vishal-beep136 one thing to consider on Windows is that you may need to use `libpg-query` version `16.2.0`, if the `U1052: file 'Makefile.msvc' not found` errors from `nmake` reported in this issue is still valid:

- https://github.com/launchql/libpg-query-node/issues/70

**Comment by Vishal-beep136** [comment]
> To get Python and other build tools installed on Windows, you may want to consider [installing Chocolatey](https://docs.chocolatey.org/en-us/choco/setup/)
> 
> If you did this, you could use the following command to install [`python`](https://community.chocolatey.org/packages/python) and [`visualstudio2022-workload-vctools`](https://community.chocolatey.org/packages/visualstudio2022-workload-vctools):
> 
> ```shell
> choco install python visualstudio2022-workload-vctools -y
> ```

wouldn't it work if I install python manually or from python official site??

**Comment by karlhorky** [comment]
Yes, should also work 👍  I just personally avoid downloading programs from websites, as it's slower, more manual work and easier to run into security problems. Using a command line package manager improves all of these things.

**Comment by Vishal-beep136** [comment]
> Yes, should also work 👍 I just personally avoid downloading programs from websites, as it's slower, more manual work and easier to run into security problems. Using a command line package manager improves all of these things.
@karlhorky Thanks for the response!
Do I also need to install this `visualstudio2022-workload-vctools`

**Comment by Vishal-beep136** [comment]
@karlhorky I used chocolatey to install and it seems that it worked thanks :))

**Comment by Vishal-beep136** [comment]
@Newbie012  @karlhorky  Btw it would be better if you mention in docs/readme that Python is required at least for windows OS I believe.

**Comment by Newbie012** [comment]
PRs are welcome 🙂

**Comment by Vishal-beep136** [comment]
@karlhorky Well rn I don't have much time but I might consider adding PR if I got free time Otherwise I might create a new issue as you mentioned! or rather should I reopen this issue itself??

**Comment by karlhorky** [comment]
New issue is better, please :)

**Comment by Vishal-beep136** [comment]
@karlhorky  UPDATE

I thought ENV might not picking it up so I hardcoded it in string value.
```
connectionUrl: postgresql://username:pass@localhost:5432/mydb?schema=public,
```

but now it showing me this error -> 

```
Internal error: database "safeql_d_\app\backend_nestjs_9d79df57" does not existeslint[@ts-safeql/check-sql](https://github.com/ts-safeql/safeql)
```

Note : Postgres is running

**Comment by karlhorky** [comment]
@Vishal-beep136 we'll take a look and respond here.

In the meantime, if you could take a few minutes to open the new issue, then we can make sure to not lose the documentation changes 👍

**Comment by Vishal-beep136** [comment]
@karlhorky I'm thinking of doing PR should I change contents in `docs/` folder or `readme.md`

**Comment by karlhorky** [comment]
Probably both, check out my comment above

**Comment by karlhorky** [comment]
@Vishal-beep136 if the PR is too much, you can also just create an issue for it, documenting the ideas from:

- [your comment](https://github.com/ts-safeql/safeql/issues/255#issuecomment-2296480292)
- [my comment](https://github.com/ts-safeql/safeql/issues/255#issuecomment-2296880957)

**Comment by karlhorky** [comment]
Ah I managed to miss your PR and this issue slipped down my list, I see it now here:

- https://github.com/ts-safeql/safeql/pull/256

I'll take a look at this and [your new issue above](https://github.com/ts-safeql/safeql/issues/255#issuecomment-2298060086) today.

**Comment by karlhorky** [comment]
@Vishal-beep136 Closing this issue - I've opened a new issue for the Prisma error you reported above:

- https://github.com/ts-safeql/safeql/issues/261
