### ISSUE TITLE
Conflicting Peer Dependencies due to outdated ESLint version

### ISSUE THREAD

**Issue by ProchaLu** [ts-safeql/safeql#258]
**Describe the bug**

The `@ts-safeql/eslint-plugin` package currently depends on TypeScript ESlint 7.18.0 that depends on ESLint 8.56.0, while the [latest available version of ESLint is 9.9.1.](https://github.com/eslint/eslint/releases). This discrepancy leads to conflicting peer dependencies when trying to install the plugin alongside other packages that require the latest version of ESLint.

```
 WARN  Issues with peer dependencies found
.
├─┬ @ts-safeql/eslint-plugin 3.4.1
│ └─┬ @typescript-eslint/utils 7.18.0
│   ├── ✕ missing peer eslint@^8.56.0
│   └─┬ @eslint-community/eslint-utils 4.4.0
│     └── ✕ missing peer eslint@"^6.0.0 || ^7.0.0 || >=8.0.0"
└─┬ eslint-config-flat-gitignore 0.3.0
  └── ✕ missing peer eslint@^9.5.0
✕ Conflicting peer dependencies:
  eslint  
```

**To Reproduce**

1. Clone [repo](https://github.com/ProchaLu/ts-safeql-peer-dependency-issue)
2. `cd ts-safeql-peer-dependency-issue`
3. Install dependencies

or

1. Initialize project `pnpm init` 
2. Install `@ts-safeql/eslint-plugin` and `eslint-config-flat-gitignore` using `pnpm add -D @ts-safeql/eslint-plugin eslint-config-flat-gitignore` 

**Expected behavior**

All dependencies should install successfully without triggering peer dependency conflicts.

**Screenshots**

<img width="450" alt="Screenshot 2024-09-05 at 12 26 24" src="https://github.com/user-attachments/assets/1a2a9935-c1ef-4adf-ad0b-ecbcc9658edc">

**Desktop (please complete the following information):**

 - OS: macOS 14.5
 - PostgreSQL version 16
- pnpm 9.9.0

**Comment by karlhorky** [comment]
Maybe moving `@typescript-eslint/utils` from `dependencies` to `peerDependencies` would be an option?

- #259
