### ISSUE TITLE
Adding `migrationsDir` to config throws ESLint error

### ISSUE THREAD

**Issue by selfagency** [ts-safeql/safeql#36]
**Describe the bug**
Adding `migrationsDir` to the plugin's rules config results in an error:

```
Error: backend/.eslintrc.js:
	Configuration for rule "@ts-safeql/check-sql" is invalid:
	Value {"migrationsDir":"./lib/migrations","databaseUrl":"postgres://postgres:postgres@localhost:5432","name":"unstoppable_website_development","operators":["queryRunner.query"]} should NOT have additional properties.
	Value {"migrationsDir":"./lib/migrations","databaseUrl":"postgres://postgres:postgres@localhost:5432","name":"unstoppable_website_development","operators":["queryRunner.query"]} should NOT have additional properties.
	Value {"migrationsDir":"./lib/migrations","databaseUrl":"postgres://postgres:postgres@localhost:5432","name":"unstoppable_website_development","operators":["queryRunner.query"]} should NOT have additional properties.
	Value {"migrationsDir":"./lib/migrations","databaseUrl":"postgres://postgres:postgres@localhost:5432","name":"unstoppable_website_development","operators":["queryRunner.query"]} should NOT have additional properties.
	Value {"migrationsDir":"./lib/migrations","databaseUrl":"postgres://postgres:postgres@localhost:5432","name":"unstoppable_website_development","operators":["queryRunner.query"]} should match some schema in anyOf.
```

**To Reproduce**

add `migrationsDir` to the config.

**Expected behavior**

For the configuration not to error.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - PostgreSQL version 11
 - Version 0.0.7

**Additional context**

**Comment by Newbie012** [comment]
That's because you can't pass both `databaseUrl` and `migrationsDir`.

[See example](https://github.com/ts-safeql/safeql/blob/main/demos/basic-migrations-raw/.eslintrc.json)

**Comment by Newbie012** [comment]
Closing due to no response from the author.

If you're having hard time trying to configure your settings, then I suggest you to use `useConfigFile` with `safeql.config.ts`.

For more info, look the release notes of [@ts-safeql/eslint-plugin@0.0.8](https://github.com/ts-safeql/safeql/releases/tag/%40ts-safeql%2Feslint-plugin%400.0.8).
