### ISSUE TITLE
Unexpected error when using type aliases / interfaces

### ISSUE THREAD

**Issue by Eprince-hub** [ts-safeql/safeql#42]
**Describe the bug**
SafeQL throws an error when using type aliases and interfaces, It doesn't recognise them when they are assigned as a type annotation. I am using it with `postgres.js`

**To Reproduce**

```ts
async function query() {
  const ids = await sql<{ id: number }[]>`SELECT id FROM animals`;

  type Animal = { id: number };
  const ids2 = await sql<Animal[]>`SELECT id FROM animals`;
}
```

**Expected behavior**
Don't throw an error when the correct type is used

**Screenshots**
![safeql-issue-image](https://user-images.githubusercontent.com/74430629/191064016-775a90a0-d4a6-4fd7-8a9f-273fc0d2ac06.png)

**Desktop (please complete the following information):**
 - OS: MAC OS
 - PostgreSQL version 13

**Additional context**

**Comment by Newbie012** [comment]
Thanks for the report. I actually have a TODO comment that should improve this. I'll see what I can do.
