### ISSUE TITLE
Tuple type annotations support

### ISSUE THREAD

**Issue by Eprince-hub** [ts-safeql/safeql#58]
**Is your feature request related to a problem? Please describe.**
There is no configuration for TypeScript tuple type

This leads to the error `Query has invalid type annotation (SafeQL does not support it. If you think it should, please open an issue)` when I use the following code
```ts
async function query() {
  type Animal = {
    id: number;
  };
  const [animal1] = await sql<[Animal]>`SELECT * FROM animals WHERE id = 1`;
  const [animal2] = await sql<[Animal | undefined]>`SELECT * FROM animals WHERE id = 1`;
}
```
![Screenshot 2022-09-26 at 18 09 19](https://user-images.githubusercontent.com/74430629/192326798-b18db813-cde5-4754-82be-4fa175712d2a.png)

![Screenshot 2022-09-26 at 18 09 39](https://user-images.githubusercontent.com/74430629/192326858-7a8928f5-2c1a-47fa-b5ec-5b9bd8ebcda2.png)

**Describe the solution you'd like**
It would be great to have the ability to use `tuples` and `arrays` together. Maybe adding this configuration to the [connections.transform?](https://safeql.dev/compatibility/postgres.js.html#:~:text=%22transform%22%3A%20%22%24%7Btype%7D%5B%5D%22)
eg. The following code should work without throwing an error
```ts
async function query() {
  type Animal = {
    id: number;
  };
  const animals = await sql<Animal[]>`SELECT * FROM animals`;
  const [animal] = await sql<[Animal]>`SELECT * FROM animals WHERE id = 1`;
}
```
**Describe alternatives you've considered**
Using it with the array it currently supports and get the single object using `array index` eg
```ts
async function query(id: number) {
  type Animal = {
    id: number;
  };
  const animals = await sql<Animal[]>`SELECT * FROM animals WHERE id = 1`;
  return animals[0];
}
```
But this can lead to an unexpected error, it won't prevent returning `undefined` index (eg.  `return animals[1]` won't throw any error from the above code even though this index will be undefined)  

**Additional context**
It should also have the ability to support `union` inside `tuple` (eg. `[Animal | undefined]` like in the following code)
```ts
async function query() {
  type Animal = {
    id: number;
  };
  const [animal] = await sql<[Animal | undefined]>`SELECT * FROM animals WHERE id = 1`;
}
```

**Comment by Newbie012** [comment]
I'm sorry but I don't see the added value to support it. How can SafeQL can determine when to return an array and when to return a tuple?

If accessing array indexes safely is something important to you, then you can use [Array.prototype.at](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at) and [noUncheckedIndexedAccess](https://www.typescriptlang.org/tsconfig#noUncheckedIndexedAccess)
