### ISSUE TITLE
Drops database table on ESLint restart

### ISSUE THREAD

**Issue by Eprince-hub** [ts-safeql/safeql#64]
**Describe the bug**
SafeQL executes the queries each time the ESLint is restarted which causes an unexpected dropping of the database table and leads to the error `Internal error: relation "animals" does not exist` immediately after restarting the ESLint.

**To Reproduce**
It executes the queries below.
e.g
```js
exports.up = async (sql) => {
  await sql`
    CREATE TABLE animals (
      id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    )
  `;
};

exports.down = async (sql) => {
  await sql`
    DROP TABLE animals
  `;
};
```
restart ESLint: `cmd + shift + P => ESLint: Restart ESLint Server`
![Screenshot 2022-09-28 at 10 17 27](https://user-images.githubusercontent.com/74430629/192726795-8b0879d2-c5b0-445e-a635-504894f3cefb.png)

**Expected behavior**
Should not execute any SQL queries

**Screenshots**
Before restarting the ESLint
![Screenshot 2022-09-28 at 10 06 21](https://user-images.githubusercontent.com/74430629/192724300-ca2c874b-ef97-4769-97e1-163a662effb2.png)
![Screenshot 2022-09-28 at 10 06 54](https://user-images.githubusercontent.com/74430629/192724413-3cd473b8-395c-45d8-ae0f-1cc84f3705d2.png)

After restarting the ESLint
![Screenshot 2022-09-28 at 10 03 56](https://user-images.githubusercontent.com/74430629/192723743-343e15f9-89a5-412a-a2b7-670bd8335868.png)
![Screenshot 2022-09-28 at 10 05 06](https://user-images.githubusercontent.com/74430629/192723974-1bb7472e-c2be-4e33-a20a-4bec7902f7eb.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - PostgreSQL version 14

**Additional context**
As far as i can tell, SafeQL tries to avoid executing the query by using [`sql``.describe()](https://github.com/ts-safeql/safeql/blob/8b227f9a6fd70b52537bf343b244a352516b2985/packages/generate/src/generate.ts#L78) 

`.describe()` should not execute the query according to [Postgres.js](https://github.com/porsager/postgres#await-sqldescriberows--1-fn---result)

But it seems SafeQL *is* actually executing the query for `DROP TABLE` which is a big problem

**Comment by Newbie012** [comment]
Fixed in [0.0.15](https://github.com/ts-safeql/safeql/releases/tag/%40ts-safeql%2Feslint-plugin%400.0.15)
