### ISSUE TITLE
Don't lint .js files

### ISSUE THREAD

**Issue by Newbie012** [ts-safeql/safeql#9]
This could probably be solved by using [ESLint's `overrides`](https://eslint.org/docs/latest/user-guide/configuring/configuration-files#how-do-overrides-work)

**Comment by 18kimn** [comment]
Can you explain the rationale here? What if we want to use SafeQL to lint JS files? Could SafeQL follow what is configured in the `checkJs` option in tsconfig? 

Is there a workaround to apply SafeQL to JS files if that's what we actually want? Using ESLint overrides doesn't seem to work as the mechanism to check this in SafeQL explicitly excludes all JS extensions
